/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppTransformsColor() {
        App classUnderTest = new App();
        int expectedRGB = 255;
        assertNotEquals("should be equal", 255, classUnderTest.transformImageByColor(255));
        }
}


