/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    String filePath = "./src/main/resources/LAND2.BMP";

    public String transformImageByColor(int rgbTobeChangedTo) {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(filePath));
            int height = img.getHeight();
            int width = img.getWidth();
            System.out.println("height" + height);
            System.out.println("width" + width);

            for (int h = 0; h < height; h++) {
                for (int w = 0; w < width; w++) {
                    int rgb = img.getRGB(w, h);
                     img.setRGB(w, h, rgbTobeChangedTo);
                }
            }
            ImageIO.write(img, "BMP", new File("./src/main/resources/newImage.bmp"));
        } catch (IOException e) {
        }
        System.out.println(img);
        return "image";
    }



























    public void transformImgDotMatrix(int rgbToSetDotMatrix){
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(filePath));
            int height = img.getHeight();
            int width = img.getWidth();

            for(int h = 0; h < height; h++){
                for(int w = 0; w < width; w++){
                    if(h % 10 == 0 && w % 10 == 0){
                        img.setRGB(w, h, rgbToSetDotMatrix);
                    }
                }
            }
            ImageIO.write(img, "BMP", new File("./src/main/resources/dotMatrix.bmp"));
        } catch(IOException e){

        }
        System.out.println(img);
    }



    

    public static void main(String[] args) {


        
        new App().transformImgDotMatrix(0);
    }

}
